---
galaxy_info:
  author: "RTE"
  description: configures the DNS with resolved
  license: Apache-2.0
  min_ansible_version: 2.9.10
  platforms:
  - name: Debian
    versions:
    - all
dependencies: []
