# Copyright (C) 2024 Savoir-faire Linux, Inc
# Copyright (C) 2024 RTE
# SPDX-License-Identifier: Apache-2.0

---
- name: Run the NICs IRQs affinity configuration tasks
  block:
    - name: Copy NIC irq affinity script
      copy:
        src: setup_nic_irq_affinity.py
        dest: /etc/systemd/system/setup_nic_irq_affinity.py
        mode: 0755
    
    - name: Copy NIC irq affinity service
      copy:
        src: setup_nic_irq_affinity.service
        dest: /etc/systemd/system/setup_nic_irq_affinity.service
        mode: 0644
    
    - name: Copy NIC irq affinity environment file
      template:
        src: setup_nic_irq_affinity.j2
        dest: /etc/default/setup_nic_irq_affinity
        mode: 0644
    
    - name: Enable and start NIC irq affinity service
      systemd:
        name: setup_nic_irq_affinity.service
        enabled: yes
        state: started
        daemon_reload: yes
  when: nics_affinity is defined
