# Copyright (C) 2022, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Deploy Cukinia's tests
  hosts:
    - cluster_machines
    - standalone_machine
    - VMs
  become: true
  gather_facts: True
  roles:
    - { role: deploy_cukinia_tests, filter: "none" }

- name: Deploy VM test files
  hosts: hypervisors
  become: true
  roles:
    - { role: deploy_cukinia_tests, filter: "hosts" }

- name: Create /etc/cukinia.conf for observers
  hosts: observers
  become: true
  roles:
    - { role: deploy_cukinia_tests, filter: "observers" }

- name: Create /etc/cukinia.conf for VMs
  hosts: VMs
  become: true
  roles:
    - { role: deploy_cukinia_tests, filter: "guests" }
