- name: "grub conf"
  lineinfile:
    dest: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX=(?!.* {{ item }})\"[^\"]*)(\".*)"
    line: '\1 {{ item }}\2'
    state: present
    backrefs: yes
  with_items:
    - ipv6.disable=1
    - efi=runtime
    - "{{ grub_append | default([]) }}"
- name: Update grub
  command: update-grub
- name: Merge lvm snapshot
  command:
    cmd: lvconvert --merge vg1/root-snap
- name: Restart for snapshot rollback
  reboot:
- name: Refresh LVM
  command:
    cmd:  lvchange --refresh vg1
- name: Recreate the snapshot
  lvol:
    vg: vg1
    lv: root
    snapshot: root-snap
    size: 21G
